Fix Warning in ArgumentRenderer #1667
styleguidist/react-styleguidist pull request #1671
Opened 2020-08-27 12:53 UTC by mitsuruog

Resolved

- Warning in ArgumentRenderer #1667

I checked the behavior of the component of the original issue after I changed the `name` to optional and found that the following error occurred.

```
DoctrineError {name: "DoctrineError", message: "Unknown type undefined"}
```

What I have found in my research is that in the above cases, `type.type` in the `returns` is lost in `getProps` in this case.
`returns` should have `NameExpression` in `type.type`.

```js
// I saw this shape.
{ 
  description: 'return a Boolean Value', 
  type: { name: 'boolean' } 
}

// but it should be this shape.
{
  title: 'returns',
  description: 'return a Boolean Value',
  type: { type: 'NameExpression', name: 'boolean' }
}
```

2020-08-31 12:13 UTC, sapegin requested changes
Thanks for the pull request!

2020-08-31 12:13 UTC, sapegin commented on src/loaders/utils/getProps.ts
> +		const returns = (method.returns || returnTags[0]) && { ...method.returns, ...returnTags[0] };
Looks like this isn't different from the previous version, unless I'm missing something (in this case we should make it more clear).

We're returning `method.returns` if it's truthy, or `returnTags[0]`.

2020-08-31 12:42 UTC, mitsuruog commented on src/loaders/utils/getProps.ts
> +		const returns = (method.returns || returnTags[0]) && { ...method.returns, ...returnTags[0] };
hmm... we need to make it more clear. in my case, `method.returns` have this object:

```js
{ 
  description: 'return a Boolean Value', 
  type: { name: 'boolean' } 
}
```

and then `returnTags[0]` have this object:

```js
{
  title: 'returns',
  description: 'return a Boolean Value',
  type: { type: 'NameExpression', name: 'boolean' }
}
```

`method.returns` will have occurred `DoctrineError` when it does not have `{ type: 'NameExpression' }`.
so I figured that merging both results would result in the intended object shape. 
But I'm also sure I don't understand enough about this logic.

What should the correct object shape of `results` be?

2020-08-31 13:54 UTC, sapegin commented on src/loaders/utils/getProps.ts
> +		const returns = (method.returns || returnTags[0]) && { ...method.returns, ...returnTags[0] };
Now I'm even more confused. So now we're overwriting anything in `method.returns` with `returnTags[0]` but previously `method.returns`  had higher priority.

If `method.returns`  is missing the type, why not add it there? Something like this:

```
const getReturns = ({method, tags}) => {
                 if (method.returns) {
                       return {
                           ...method.returns,
                           type: { type: 'NameExpression', ...method.returns.type } 
                       }
                 }

		const returnTags = getMergedTag(
			tags as TagProps,
			JS_DOC_METHOD_RETURN_TAG_SYNONYMS
		) as TagParamObject[];

                 return returnTags[0];
}
```

2020-08-31 15:20 UTC, mitsuruog commented on src/loaders/utils/getProps.ts
> +		const returns = (method.returns || returnTags[0]) && { ...method.returns, ...returnTags[0] };
> previously `method.returns` had higher priority.

I got it. I’ll add a change on the `method.returns` side.

2020-09-06 14:52 UTC, mitsuruog commented
@sapegin please review me.

2020-09-07 09:57 UTC, sapegin approved these changes
🦄

2020-09-07 09:59 UTC, merged