Add expand and allow custom root section options
styleguidist/react-styleguidist pull request #1689
Opened 2020-09-07 20:23 UTC by josephrexme

This addresses #1674 which allows user set and `expand` setting for each root section. It also sends all custom options from the user through to be usable

2020-09-08 05:36 UTC, sapegin requested changes
Thanks for the pull request! Please update the docs and tests.

2020-09-08 09:59 UTC, josephrexme commented
Thanks for taking a look @sapegin . I have just added tests. The [syntax highlighting test here](https://github.com/styleguidist/react-styleguidist/pull/1689/files#diff-d56e2054ed9db0792599da8bcf6ce89b) that I modified was failing even though I hadn't touched it so I made it look like the value it was expecting. I can revert that if it's not needed. I don't know if I also had to include an updated snapshot

2020-09-08 10:38 UTC, sapegin commented
> The syntax highlighting test here that I modified was failing even though I hadn't touched it so I made it look like the value it was expecting. I can revert that if it's not needed. I don't know if I also had to include an updated snapshot

This is because Prism was updated at some point, and the snapshot is already fixed in master.

2020-09-08 10:44 UTC, sapegin requested changes

2020-09-08 10:44 UTC, sapegin commented on docs/Configuration.md
> +## `expand`
I'm confused: this isn't a global configuration option, right? If so, we should document it here:

https://github.com/styleguidist/react-styleguidist/blob/master/docs/Components.md#sections

2020-09-08 10:44 UTC, sapegin commented on src/loaders/utils/getSections.ts
>  		name: section.name,
We don't need this line anymore, and also `description` and `external` below.

2020-09-08 14:10 UTC, josephrexme commented on docs/Configuration.md
> +## `expand`
Thank you!

2020-09-08 14:20 UTC, josephrexme commented
> > The syntax highlighting test here that I modified was failing even though I hadn't touched it so I made it look like the value it was expecting. I can revert that if it's not needed. I don't know if I also had to include an updated snapshot
> 
> This is because Prism was updated at some point, and the snapshot is already fixed in master.

To be clear, should I undo my change with the **highlightCode.spec.ts** file?

2020-09-08 14:22 UTC, sapegin commented
Try to merge master into your branch.

2020-09-09 12:04 UTC, merged

2020-09-09 13:05 UTC, josephrexme commented
Thanks for the reviews and accepting my PR @sapegin