chore: Add GitHub workflow files
styleguidist/react-styleguidist pull request #1719
Opened 2020-11-26 15:29 UTC by balazsmatepetro

Closes #1713

2020-11-26 18:54 UTC, sapegin requested changes
Thanks! 🦄 

We'll also need to remove the [Travis config file](https://github.com/styleguidist/react-styleguidist/blob/master/.travis.yml) once we're sure this thing is working.

2020-11-26 18:54 UTC, sapegin commented on .github/workflows/coverage.yml
> +      - name: Checkout project
Let's remove all these names: they are mostly redundant and don't add any useful information. The only useful ones are with parameters, like `Use Node.js ${{ matrix.node-version }}`.

2020-11-26 18:54 UTC, sapegin commented on .github/workflows/coverage.yml
> +    name: Check
Let's remove all these names: if there's one job they will repeat the workflow name, which isn't useful, or "Check" which is even less helpful.

2020-11-26 18:54 UTC, sapegin commented on .github/workflows/coverage.yml
> +          token: ${{ secrets.CODECOV_TOKEN }}
This is only needed for private repositories, and we don't have this value anyway.

```suggestion
```

2020-11-26 18:54 UTC, sapegin commented on .github/workflows/coverage.yml
> +          fail_ci_if_error: true
I'd probably keep the default `false` here. What do you think?

```suggestion
```

2020-11-26 18:54 UTC, sapegin commented on .github/workflows/node.js.yml
> +      - name: lint
No need to run lint, type check, and especially integrations (they take a lot of time), in every Node.js version: in the current setup, we run them only once. Looks like we need a separate workflow for them.

2020-11-26 18:54 UTC, sapegin commented on .github/workflows/release.yml
> +      - run: npm ci
```suggestion
      - run: npm ci

```

2020-11-26 18:54 UTC, sapegin commented on Readme.md
>  **Isolated React component development environment with a living style guide**
```suggestion
**Isolated React component development environment with a living style guide**

```

2020-11-26 18:54 UTC, sapegin commented on tsconfig.json
> +  "files": ["dangerfile.ts"],
Let's fix the indentation in this file: it should be two spaces, not sure why we have tabs here.

2020-11-26 18:54 UTC, sapegin commented on .github/workflows/node.js.yml
> +name: CI
I don't see where we run tests here.

https://github.com/styleguidist/react-styleguidist/blob/9c2ca5b33a2d6b5008154521ed7a41f52616bbd1/.travis.yml#L12-L13

2020-11-30 09:14 UTC, balazsmatepetro commented on .github/workflows/coverage.yml
> +      - name: Checkout project
75ea2be4b5f5b9994de9eaa3e26167be85925d21

2020-11-30 09:14 UTC, balazsmatepetro commented on .github/workflows/coverage.yml
> +    name: Check
75ea2be4b5f5b9994de9eaa3e26167be85925d21

2020-11-30 09:15 UTC, balazsmatepetro commented on .github/workflows/coverage.yml
> +          token: ${{ secrets.CODECOV_TOKEN }}
6f1ea5a99d236e49ffb989c62795538fa6f88ba4

2020-11-30 09:15 UTC, balazsmatepetro commented on .github/workflows/coverage.yml
> +          fail_ci_if_error: true
7aa379c1924110995ba31c92e78de8d6a7c5bbe8

2020-11-30 09:15 UTC, balazsmatepetro commented on Readme.md
>  **Isolated React component development environment with a living style guide**
c712f0e020329ca052679cfcaee6866fa883326b

2020-11-30 09:19 UTC, balazsmatepetro commented on .github/workflows/node.js.yml
> +      - name: lint
a6070739a11af9b7d1a563181e52ce8a764f82eb

2020-11-30 09:22 UTC, balazsmatepetro commented on .github/workflows/node.js.yml
> +name: CI
1ecbc86cb99f0f809d2fbba5a39e3f2054b12fea

2020-11-30 09:22 UTC, balazsmatepetro commented on tsconfig.json
> +  "files": ["dangerfile.ts"],
20df7421c97184a3d5fec6ccb6b5c8afda9449ec

2020-11-30 09:22 UTC, balazsmatepetro commented on .github/workflows/release.yml
> +      - run: npm ci
Not really related to this one, but the new line was added when I did this change:

2883cbd85a84c6c30273817b3d02f287b87ced12

2020-11-30 10:45 UTC, sapegin approved these changes
Approving with one little change.

2020-11-30 10:45 UTC, sapegin commented on .github/workflows/node.js.yml
> +          npm run build:sections
We don't need this here.

```suggestion
```

2020-11-30 10:45 UTC, sapegin commented on .github/workflows/release.yml
> +      - run: npm ci
I believe accepting changes would make the whole process faster for both of us ;-)

2020-11-30 12:11 UTC, okonet commented on tsconfig.json
> +  "files": ["dangerfile.ts"],
This can and should be handled by lint-staged and prettier. Just saying ;)

2020-12-02 13:41 UTC, okonet approved these changes

2020-12-02 13:43 UTC, merged

2020-12-04 08:13 UTC, sapegin commented
Looks like it works!