Env is hardcoded to "production" which causes React v17 to fail building properly
styleguidist/react-styleguidist pull request #1727
Opened 2020-12-08 21:38 UTC by Edu93Jer

closes issue #1721

Fix issue #1721 now the env variable is not hardcoded to 'production'

2020-12-10 08:15 UTC, sapegin requested changes
Thanks for the pull request! Please have a look at the failing CI.

2020-12-10 08:15 UTC, sapegin commented on src/scripts/make-webpack-config.ts
> +type EnvType = 'development' | 'production' | 'none';
This type is available in webpack:

```suggestion
type Mode = Configuration['mode'];
```

https://github.com/styleguidist/react-styleguidist/blob/04d900d7271761c257eacf57bb5e7279ded3525a/src/scripts/make-webpack-config.ts#L16

2020-12-10 08:15 UTC, sapegin commented on src/scripts/make-webpack-config.ts
> +	env = (process.env.NODE_ENV as EnvType) || env;
Please don't overwrite function parameters.

2020-12-29 04:03 UTC, Edu93Jer commented
Hi @sapegin how are you, first of all merry x-mas, just asking how is the review of the PR going, I made the changes and now the check passes correctly.

2020-12-29 06:42 UTC, sapegin commented on src/scripts/build.ts
> +	return webpack(makeWebpackConfig(config, 'development'), (err, stats) => {
I'm not sure about this change now: this will increase the bundle size for every generated style guide, which seems unnecessary. Would it make more sense to for `NODE_ENV` for override `env` in `make-webpack-config.ts` when it's provided?

2020-12-30 05:27 UTC, Edu93Jer commented on src/scripts/build.ts
> +	return webpack(makeWebpackConfig(config, 'development'), (err, stats) => {
Sorry for the late replay @sapegin I was a little busy today, so isn't that the proposal @jasonwilliams did `env = process.env.NODE_ENV || env` of course now would be something like this `env = (process.env.NODE_ENV as Mode) || env` or what do you mean with override `env`?

2020-12-30 07:06 UTC, sapegin commented on src/scripts/make-webpack-config.ts
> +	process.env.NODE_ENV = (process.env.NODE_ENV as Mode) || env;
I think it should be something like this:

```suggestion
export default function (config: Rsg.SanitizedStyleguidistConfig, envRaw: Mode): Configuration {
	const env = (process.env.NODE_ENV as Mode) || envRaw;
```

2020-12-30 09:15 UTC, jasonwilliams commented on src/scripts/build.ts
> +	return webpack(makeWebpackConfig(config, 'development'), (err, stats) => {
It should be ok to stick with “production” here, so long as it passes through and it’s overridable. So I think you can leave this bit as it is

2020-12-30 19:35 UTC, Edu93Jer commented on src/scripts/make-webpack-config.ts
> +	process.env.NODE_ENV = (process.env.NODE_ENV as Mode) || env;
We can try, I will do the commit from here

2021-06-18 23:59 UTC, closed without merging