Add Elementz in Showcase
styleguidist/react-styleguidist pull request #1845
Opened 2021-06-21 14:13 UTC by el1s7

Thanks for making styleguidist <3 !
 I've used it for documenting my latest project https://github.com/elementz-ui/elementz and would like to include it in the showcase examples if possible.

2021-06-23 12:11 UTC, sapegin requested changes
Thanks!

2021-06-23 12:11 UTC, sapegin commented on site/src/pages/index.js
> +		image: 'https://elementz.style/showcase.PNG'
Please update an existing image and make it the same size and style as the other images (it should be an actual screenshot). Don't forget to optimize an image too.

Also, no need to change the order.

2021-06-23 12:36 UTC, el1s7 commented on site/src/pages/index.js
> +		image: 'https://elementz.style/showcase.PNG'
I have resized it to 590x473. I'm not sure what you mean by style and order, it is an actual screenshot, if you mean to use the Light theme then you can add this instead https://elementz.style/showcase_white.png

2021-06-23 12:39 UTC, sapegin commented on site/src/pages/index.js
> +		image: 'https://elementz.style/showcase.PNG'
Yup, light theme would better match the other screenshots. And it's also the default.

By order I mean the order or examples on the page.

2021-06-23 12:46 UTC, el1s7 commented on site/src/pages/index.js
> +		image: 'https://elementz.style/showcase.PNG'
Feel free to edit it

2021-07-05 19:11 UTC, el1s7 commented on site/src/pages/index.js
> +		image: 'https://elementz.style/showcase.PNG'
@sapegin

2022-04-27 22:18 UTC, closed without merging